### ISSUE TITLE
can't run it on macOS/linux, some calls platform dependent

### ISSUE THREAD

**Issue by ms03831** [hasanbaig/GeneTech#1]
The following code in **[Gateway.py](https://github.com/hasanbaig/GeneTech/blob/master/Src/Python/Gateway.py)** uses the taskkill call which is a windows command and makes the build strongly platform dependent. 
`os.system("taskkill /im javaw.exe /f")`

**Comment by hasanbaig** [comment]
Yes, it is currently tested on Windows Platform. I am currently working on its Darwin's release and will make it available soon.

**Comment by ms03831** [comment]
This
