### ISSUE TITLE
redundant function calls in functions.py

### ISSUE THREAD

**Issue by ms03831** [hasanbaig/GeneTech#2]
The baseList() function is being called multiple times, which is redundant. 
![image](https://user-images.githubusercontent.com/31242863/77810188-098f5000-70b5-11ea-952a-57d7c17ba6aa.png)
Replacing these function calls with a variable may not result in a significant improvement in the performance, but will get rid of the redundancy, and improve code readability.

**Comment by hasanbaig** [comment]
@MAbhutto Would you want to comment on this ?
